In [34]:
import numpy as np
import cv2 as cv
import pandas
import json
import glob, os
import matplotlib.pyplot as plt

In [48]:
def Write_json_anotations(seg_id,img_id,dictionary2,area,bb_size):
    annotations={"id":seg_id, "image_id":img_id, 
                 "category_id":1,
                 "segmentation":[dictionary2],
                 "area":area,
                 "bbox": bb_size,
                 "iscrowd":0, "attributes":{"occluded": False}}
    dictionary["annotations"].append(annotations)

def Write_json_image_dict(img_id, img, filename):
    image_dict={"id":img_id, "width":img.shape[1], "height":img.shape[0], "file_name":filename,"license":0,"flickr_url":"","coco_url":"","date_captured":0 }
    dictionary["images"].append(image_dict)


In [49]:
dictionary ={
    "licenses":[{"name": "", "id": 0, "url":""}],
    "info":{ "contributor": "", "date_created":"", "description":"", "url":"", "version":"", "year": ""},
    "categories" : [{"id":1, "name":"roi", "supercategory":""}],
    "images" : [],
    "annotations" : [],
}
dictionary2 ={}

In [50]:
os.chdir("F:/Dataset/Mammography/3_1")
img_id= 0
seg_id=1
old_patient=""
actual_patient="/"
for file in glob.glob("*_mask.png"):
    countour=[]
    img = cv.imread(f'F:/Dataset/Mammography/3_1/{file}',0)
    kernel = np.ones((3,3), np.uint8)
    img_erosion = cv.erode(img, kernel, iterations=1)
    img_dilation = cv.dilate(img, kernel, iterations=1)
    contours, hierarchy = cv.findContours(img_dilation, cv.RETR_EXTERNAL, cv.CHAIN_APPROX_NONE)
    countour=contours[0]
    if len(contours) >1:
        for i in range(len(contours)):
            if(len(countour)<len(contours[i])):
                countour=contours[i]
            
    filesplit = file.split("_")
    filename= filesplit[0]+"_"+filesplit[1]+"_"+filesplit[2]+"_"+filesplit[3]+".png"
    # try:
    #     filesplit = glob.glob("*_mask.png")[i+1].split("_")
    # except:
    #     filesplit = glob.glob("*_mask.png")[i].split("_")
        
    actual_patient = filesplit[0]+"_"+filesplit[1]+"_"+filesplit[2]+"_"+filesplit[3]
    
    if old_patient != actual_patient:
        img_id=img_id+1
        old_patient=actual_patient
        Write_json_image_dict(img_id,img,filename)
    
    print(file)
    print(img_id)
    index=0
    X_ax = []
    Y_ax = []
    all_points=[]
    for i in countour:
        for j in range(2):
            all_points.append(np.int64(i[0][j]).item())
            
        X_ax.append(i[0][0])
        Y_ax.append(i[0][1])
    dictionary2[0]=all_points
    all_points_tuple=tuple(all_points)
    ponto_menor=[np.int64(min(X_ax)).item()-30,np.int64(min(Y_ax)).item()-30]
    ponto_maior=[np.int64(max(X_ax)).item()+30, np.int64(max(Y_ax)).item()+30]
    # ponto_menor=np.int16(ponto_menor).item()
    # ponto_maior=np.int16(ponto_maior).item()
    bb_size=[ponto_menor[0],ponto_menor[1], ponto_maior[0]-ponto_menor[0], ponto_maior[1]-ponto_menor[1]]
    bb_size=tuple(bb_size)
    area=cv.contourArea(countour)
    # print(area)
    area=np.int64(area).item()
    # print(area)
    Write_json_anotations(seg_id,img_id,all_points_tuple,area,bb_size)
    seg_id=seg_id+1
    
        

P_00001_LEFT_CC_0_mask.png
1
P_00001_LEFT_MLO_0_mask.png
2
P_00004_LEFT_CC_0_mask.png
3
P_00004_LEFT_MLO_0_mask.png
4
P_00004_RIGHT_MLO_0_mask.png
5
P_00009_RIGHT_CC_0_mask.png
6
P_00009_RIGHT_MLO_0_mask.png
7
P_00015_LEFT_MLO_0_mask.png
8
P_00016_LEFT_CC_0_mask.png
9
P_00016_LEFT_MLO_0_mask.png
10
P_00017_LEFT_CC_0_mask.png
11
P_00017_LEFT_MLO_0_mask.png
12
P_00018_RIGHT_CC_0_mask.png
13
P_00018_RIGHT_MLO_0_mask.png
14
P_00021_LEFT_CC_0_mask.png
15
P_00021_LEFT_MLO_0_mask.png
16
P_00021_RIGHT_CC_0_mask.png
17
P_00021_RIGHT_MLO_0_mask.png
18
P_00023_RIGHT_CC_0_mask.png
19
P_00023_RIGHT_MLO_0_mask.png
20
P_00026_LEFT_CC_0_mask.png
21
P_00026_LEFT_MLO_0_mask.png
22
P_00027_RIGHT_CC_0_mask.png
23
P_00027_RIGHT_MLO_0_mask.png
24
P_00032_RIGHT_CC_0_mask.png
25
P_00032_RIGHT_MLO_0_mask.png
26
P_00034_RIGHT_CC_0_mask.png
27
P_00034_RIGHT_MLO_0_mask.png
28
P_00037_RIGHT_CC_0_mask.png
29
P_00037_RIGHT_MLO_0_mask.png
30
P_00039_RIGHT_CC_0_mask.png
31
P_00039_RIGHT_MLO_0_mask.png
32
P_00041_LEFT_

In [51]:
os.chdir("C:/Users/Raul/Desktop/Tese/CBIS")
# Serializing json 
json_object = json.dumps(dictionary, indent = 1,separators=(',',': '))
  
# Writing to sample.json
with open("sample.json", "w") as outfile:
    outfile.write(json_object)

In [29]:
type(ponto_menor[1]),type(bb_size[0]),type(area),type(seg_id),type(img_id)
# type(dictionary2["0"])
type(img.shape[0]),type(filename)

(int, str)

# Analisar contornos das mascaras

In [38]:
# img = cv.imread(f'F:/Dataset/Mammography/3_1/P_00001_LEFT_CC_0_mask.png',0)
img = cv.imread(f'F:/Dataset/Mammography/3_1/P_00059_LEFT_MLO_0_mask.png',0)


kernel = np.ones((3,3), np.uint8)
img_erosion = cv.erode(img, kernel, iterations=1)
img_dilation = cv.dilate(img, kernel, iterations=1)
contours, hierarchy = cv.findContours(img_dilation, cv.RETR_EXTERNAL, cv.CHAIN_APPROX_NONE)
cv.drawContours(img, contours, -1, (255,0, 255), 10)


img = cv.resize(img, (960, 540))  
cv.imshow("outline contour & centroid", img)
cv.waitKey(0)
cv.destroyAllWindows()

In [44]:
len(contours[1])

942

In [40]:
contours

(array([[[1089, 3007]],
 
        [[1089, 3008]],
 
        [[1089, 3009]],
 
        [[1090, 3010]],
 
        [[1091, 3010]],
 
        [[1092, 3010]],
 
        [[1093, 3010]],
 
        [[1094, 3010]],
 
        [[1095, 3010]],
 
        [[1096, 3010]],
 
        [[1096, 3009]],
 
        [[1096, 3008]],
 
        [[1096, 3007]],
 
        [[1095, 3007]],
 
        [[1094, 3007]],
 
        [[1093, 3008]],
 
        [[1092, 3007]],
 
        [[1091, 3007]],
 
        [[1090, 3007]]], dtype=int32),
 array([[[ 994, 2961]],
 
        [[ 994, 2962]],
 
        [[ 994, 2963]],
 
        ...,
 
        [[ 997, 2962]],
 
        [[ 996, 2961]],
 
        [[ 995, 2961]]], dtype=int32))

In [46]:
raul = []
raul = contours[0]
raul

array([[[1089, 3007]],

       [[1089, 3008]],

       [[1089, 3009]],

       [[1090, 3010]],

       [[1091, 3010]],

       [[1092, 3010]],

       [[1093, 3010]],

       [[1094, 3010]],

       [[1095, 3010]],

       [[1096, 3010]],

       [[1096, 3009]],

       [[1096, 3008]],

       [[1096, 3007]],

       [[1095, 3007]],

       [[1094, 3007]],

       [[1093, 3008]],

       [[1092, 3007]],

       [[1091, 3007]],

       [[1090, 3007]]], dtype=int32)

In [5]:
contours[0][851][0][0]

559

In [68]:
index=0
string="{"
X_ax = []
Y_ax = []
for i in contours[0]:
    for j in range(2):
        if index != 0:
            string+=","
        string+=f'{index}'+":"+str(i[0][j])
        index+=1
    X_ax.append(i[0][0])
    Y_ax.append(i[0][1])
string+="}"
ponto_menor=[min(X_ax)-30, min(Y_ax)-30]
ponto_maior=[max(X_ax)+30, max(Y_ax)+30]
print(ponto_menor,ponto_maior)
ponto_maior[0]-ponto_menor[0], ponto_maior[1]-ponto_menor[1]

[621, 3054] [994, 3346]


(373, 292)

In [10]:
dictionary2 ={}

In [11]:
os.chdir("C:/Users/Raul/Desktop/Tese/CBIS")
# Serializing json 
json_object = json.dumps(dictionary2, indent = 4)
  
# Writing to sample.json
with open("sample.json", "w") as outfile:
    outfile.write(json_object)
dictionary2

{}

In [25]:
type(all_points[0])

int

In [20]:

index=0
arroz=(1,2,3,4,5,6,7,8,9)
dictionary2={"segmenta":[arroz]}
os.chdir("C:/Users/Raul/Desktop/Tese/CBIS")
# Serializing json 
json_object = json.dumps(dictionary2, indent = 4)
  
# Writing to sample.json
with open("sample1.json", "w") as outfile:
    outfile.write(json_object)
type(arroz)

tuple

In [26]:
arroz1=[1,2,3,4,5,6,7,8,9]
type(arroz1)
arroz2=tuple(arroz1)
type(arroz2)
arroz2

(1, 2, 3, 4, 5, 6, 7, 8, 9)

In [125]:
index=0
X_ax = []
Y_ax = []
arroz=()
for i in contours[0]:
    for j in range(2):
        dictionary2[index]=np.int16(i[0][j]).item()
        # string+=f'{index}'+":"+str(i[0][j])
        index+=1
    X_ax.append(i[0][0])
    Y_ax.append(i[0][1])
# string+="}"
ponto_menor=[min(X_ax)-30, min(Y_ax)-30]
ponto_maior=[max(X_ax)+30, max(Y_ax)+30]
print(ponto_menor,ponto_maior)
ponto_maior[0]-ponto_menor[0], ponto_maior[1]-ponto_menor[1]

[621, 3054] [994, 3346]


(373, 292)

In [126]:
dictionary["annotations"]=[dictionary2]
dictionary
os.chdir("C:/Users/Raul/Desktop/Tese/CBIS")
# Serializing json 
json_object = json.dumps(dictionary, indent = 4)
  
# Writing to sample.json
with open("sample.json", "w") as outfile:
    outfile.write(json_object)

In [8]:
plt.figure(figsize = (200,100))
plt.imshow(img,'gray')